In [48]:
import numpy as np
import pandas as pd
from scipy import sparse

In [49]:
ratings=pd.read_csv(r'C:\Users\Shivam\Desktop\Mckinsey\Clustering\ml-latest-small\ratings.csv')

In [50]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [51]:
movies=pd.read_csv(r'C:\Users\Shivam\Desktop\Mckinsey\Clustering\ml-latest-small\movies.csv')

In [52]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [53]:
data=pd.merge(ratings,movies,on='movieId')

In [54]:
data.head()

,userId,movieId,rating,timestamp,title,genres
0,1,1,4.0,964982703,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,5,1,4.0,847434962,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
2,7,1,4.5,1106635946,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
3,15,1,2.5,1510577970,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
4,17,1,4.5,1305696483,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy

In [55]:
data=data.drop(['timestamp','genres'],axis=1)

In [56]:
data

        userId  movieId  rating                             title
0            1        1     4.0                  Toy Story (1995)
1            5        1     4.0                  Toy Story (1995)
2            7        1     4.5                  Toy Story (1995)
3           15        1     2.5                  Toy Story (1995)
4           17        1     4.5                  Toy Story (1995)
...        ...      ...     ...                               ...
100831     610   160341     2.5                  Bloodmoon (1997)
100832     610   160527     4.5  Sympathy for the Underdog (1971)
100833     610   160836     3.0                     Hazard (2005)
100834     610   163937     3.5                Blair Witch (2016)
100835     610   163981     3.5                         31 (2016)

[100836 rows x 4 columns]

In [57]:
#Creating a pivot table
data_pivot=pd.pivot_table(data,index='userId',columns='title',values='rating')

In [58]:
userRatings = data_pivot.dropna(thresh=10, axis=1).fillna(0,axis=1)

In [59]:
userRatings

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
607,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
608,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,4.5,3.5,0.0
609,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
610,0.0,3.5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,...,3.5,0.0,0.0,5.0,3.5,4.0,4.0,0.0,2.0,0.0

In [60]:
def standardize(row):
    return (row-row.mean()/row.max()-row.min())
    
userRatings=userRatings.apply(standardize).T

In [61]:
userRatings

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,...,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705,-0.017705
(500) Days of Summer (2009),-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,...,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,-0.050492,3.449508
10 Cloverfield Lane (2016),-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,...,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,-0.016885,3.983115
10 Things I Hate About You (1999),-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459,...,-0.062459,-0.062459,2.937541,-0.062459,4.937541,-0.062459,-0.062459,-0.062459,-0.062459,-0.062459
"10,000 BC (2008)",-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,...,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852,-0.018852
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoolander (2001),-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,...,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,-0.062131,2.937869,-0.062131,3.937869
Zootopia (2016),-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,...,4.459180,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,-0.040820,3.959180
eXistenZ (1999),-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,-0.027869,...,-0.027869,-0.027869,4.972131,-0.027869,-0.027869,-0.027869,-0.027869,4.472131,-0.027869,-0.027869
xXx (2002),-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,0.972746,-0.027254,...,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,-0.027254,3.472746,-0.027254,1.972746
¡Three Amigos! (1986),3.973279,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,...,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721,-0.026721

In [62]:
from sklearn.metrics.pairwise import cosine_similarity

In [63]:
corrMatrix=pd.DataFrame(cosine_similarity(userRatings),index=userRatings.index,columns=userRatings.index)

In [64]:
corrMatrix

title,"'burbs, The (1989)",(500) Days of Summer (2009),10 Cloverfield Lane (2016),10 Things I Hate About You (1999),"10,000 BC (2008)",101 Dalmatians (1996),101 Dalmatians (One Hundred and One Dalmatians) (1961),12 Angry Men (1957),12 Years a Slave (2013),127 Hours (2010),...,Zack and Miri Make a Porno (2008),Zero Dark Thirty (2012),Zero Effect (1998),Zodiac (2007),Zombieland (2009),Zoolander (2001),Zootopia (2016),eXistenZ (1999),xXx (2002),¡Three Amigos! (1986)
title,,,,,,,,,,,,,,,,,,,,,
"'burbs, The (1989)",1.000000,0.086928,-0.008428,0.167556,0.026795,0.112297,0.243882,0.063260,0.024770,0.025111,...,0.035368,0.047057,0.148163,0.173642,0.127035,0.077312,0.025886,0.203163,0.078863,0.365934
(500) Days of Summer (2009),0.086928,1.000000,0.162857,0.308246,0.212890,0.186463,0.179393,0.201092,0.157048,0.221669,...,0.392381,0.198161,0.091769,0.438066,0.386303,0.287615,0.244952,0.082489,0.262600,0.154255
10 Cloverfield Lane (2016),-0.008428,0.162857,1.000000,0.022072,0.125045,0.031759,0.009058,0.059386,-0.009034,0.284616,...,0.255705,0.111984,-0.008327,0.288589,0.261274,0.216106,0.333470,0.192469,0.111916,0.021727
10 Things I Hate About You (1999),0.167556,0.308246,0.022072,1.000000,0.263968,0.262351,0.250294,0.067107,0.117644,0.073070,...,0.267630,0.129110,0.156593,0.133150,0.204191,0.320612,0.089847,0.151127,0.158846,0.143195
"10,000 BC (2008)",0.026795,0.212890,0.125045,0.263968,1.000000,0.253077,0.140955,0.085853,-0.010624,0.103974,...,0.272986,0.100676,0.108305,0.203082,0.261792,0.259721,0.114159,0.104310,0.216446,0.100899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zoolander (2001),0.077312,0.287615,0.216106,0.320612,0.259721,0.225272,0.310070,0.171385,0.045706,0.119440,...,0.326625,0.263349,0.022763,0.276482,0.337553,1.000000,0.145545,0.128239,0.358426,0.142170
Zootopia (2016),0.025886,0.244952,0.333470,0.089847,0.114159,0.091028,0.113085,0.097907,0.084366,0.244412,...,0.304788,0.174661,0.033600,0.242321,0.327761,0.145545,1.000000,0.072727,0.221144,0.048893
eXistenZ (1999),0.203163,0.082489,0.192469,0.151127,0.104310,0.078528,0.114561,0.034550,0.021150,0.146227,...,0.108026,0.046039,0.182945,0.170724,0.101105,0.128239,0.072727,1.000000,0.180807,0.159192
xXx (2002),0.078863,0.262600,0.111916,0.158846,0.216446,0.182338,0.270839,0.105648,0.054482,0.169530,...,0.286186,0.207324,0.096744,0.231546,0.228806,0.358426,0.221144,0.180807,1.000000,0.086811
¡Three Amigos! (1986),0.365934,0.154255,0.021727,0.143195,0.100899,0.110370,0.198986,0.136960,0.024007,0.024361,...,0.133337,0.082779,0.176441,0.215058,0.192190,0.142170,0.048893,0.159192,0.086811,1.000000

In [71]:
corrMatrix['10,000 BC (2008)'].sort_values(ascending=False)

Index(['10,000 BC (2008)', 'Incredible Hulk, The (2008)',
       '2 Fast 2 Furious (Fast and the Furious 2, The) (2003)',
       'Green Lantern (2011)', 'Star Trek Into Darkness (2013)',
       'Whole Nine Yards, The (2000)', 'Live Free or Die Hard (2007)',
       'The Hunger Games: Catching Fire (2013)',
       'Rise of the Planet of the Apes (2011)',
       'Harold and Kumar Go to White Castle (2004)',
       ...
       'Broadcast News (1987)',
       'Monty Python's And Now for Something Completely Different (1971)',
       'Arsenic and Old Lace (1944)', 'Hoop Dreams (1994)',
       'Madness of King George, The (1994)',
       'Like Water for Chocolate (Como agua para chocolate) (1992)',
       'Indian in the Cupboard, The (1995)',
       'Postman, The (Postino, Il) (1994)', 'Nine Months (1995)',
       'English Patient, The (1996)'],
      dtype='object', name='title', length=2269)

In [72]:
def get_similar(movie,rating):
    if rating>2.5:
        return corrMatrix[movie].sort_values(ascending=False).head(50)
    else:
        return corrMatrix[movie]*(-1).sort_values(ascending=False).head(50)

In [74]:
get_similar('2 Fast 2 Furious (Fast and the Furious 2, The) (2003)',5.0)

title
2 Fast 2 Furious (Fast and the Furious 2, The) (2003)                          1.000000
xXx (2002)                                                                     0.545141
30 Days of Night (2007)                                                        0.521996
Die Another Day (2002)                                                         0.521810
Snakes on a Plane (2006)                                                       0.520495
Fast and the Furious, The (2001)                                               0.511269
Kung Fu Hustle (Gong fu) (2004)                                                0.500517
Wanted (2008)                                                                  0.494071
S.W.A.T. (2003)                                                                0.493112
Rat Race (2001)                                                                0.492601
The Scorpion King (2002)                                                       0.490095
Mr. Deeds (2002)                                                               0.482311
Smokin' Aces (2006)                                                            0.480757
Mummy Returns, The (2001)                                                      0.480154
Resident Evil (2002)                                                           0.475898
40 Days and 40 Nights (2002)                                                   0.475513
Fast & Furious (Fast and the Furious 4, The) (2009)                            0.473998
Paycheck (2003)                                                                0.468582
Charlie's Angels: Full Throttle (2003)                                         0.467349
Reign of Fire (2002)                                                           0.460140
Fantastic Four (2005)                                                          0.459739
Rundown, The (2003)                                                            0.458040
Jumper (2008)                                                                  0.457071
Crank (2006)                                                                   0.454156
Mission: Impossible III (2006)                                                 0.447073
Transporter, The (2002)                                                        0.440719
Fast and the Furious: Tokyo Drift, The (Fast and the Furious 3, The) (2006)    0.435987
School of Rock (2003)                                                          0.432183
Disturbia (2007)                                                               0.426797
Dungeons & Dragons (2000)                                                      0.425248
Dude, Where's My Car? (2000)                                                   0.422331
Hellboy (2004)                                                                 0.418768
Meet the Fockers (2004)                                                        0.418233
Blade: Trinity (2004)                                                          0.417327
Evolution (2001)                                                               0.417326
Ultraviolet (2006)                                                             0.415009
Team America: World Police (2004)                                              0.411766
Transporter 2 (2005)                                                           0.411213
Zoolander (2001)                                                               0.408254
Swordfish (2001)                                                               0.406472
Sum of All Fears, The (2002)                                                   0.406454
Troy (2004)                                                                    0.405328
Underworld (2003)                                                              0.404991
Tuxedo, The (2002)                                                             0.404318
Death Proof (2007)                                                             0.399160
Chronicles of Riddick, The (2004)                                              0.398896
Rush Hour 2 (2001)                                                             0.396937
I Now Pronounce You Chuck and Larry (2007)                                     0.393673
10,000 BC (2008)                                                               0.393302
Shanghai Knights (2003)                                                        0.393238
Name: 2 Fast 2 Furious (Fast and the Furious 2, The) (2003), dtype: float64